name: Run Python script daily

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時（UTC）に実行
  workflow_dispatch:     # 手動でも実行できるようにする

permissions:
  contents: write  # CSVをpushするために必要！

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python price_log.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add price_log.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update price log"
            git push origin main  # ブランチ名が `main` の場合。`master` の場合は書き換えてください
